### ISSUE TITLE
gamestate.current should not be a function

### ISSUE THREAD

**Issue by farzher** [vrld/hump#48]
It's more convenient and better performance `gamestate.current().world` vs `gamestate.current.world`

You always know when state changes, so you can update `current` then. State doesn't change often so using cpu cycles there is better than every time it's accessed

Everywhere you're using `stack[#stack]` in source you can replace with `GS.current` for cleaner code and again performance

**Comment by vrld** [comment]
No, because:

1. The overhead is negligible. Please provide time measurements if you believe otherwise.
2. Making it a reference to the current state implies you can change it by `GS.current = to` - which you cannot, unless
3. Making it a pseudo-reference via `__index` and `__newindex` has even more "overhead" than a function call.
