### ISSUE TITLE
[hump.gamestates] löve 0.11 random quits on errors

### ISSUE THREAD

**Issue by zorggn** [vrld/hump#95]
Some people have been noticing this behavior when using hump.gamestates; instead of the default error handler being called, it will just quit the application; 0.11 renamed love.errhand to love.errorhandler, so that one string should be changed in gamestate.lua to work correctly with the current version.

https://github.com/vrld/hump/blob/master/gamestate.lua#L78

Edit: That may not be the whole story though: https://love2d.org/forums/viewtopic.php?f=4&t=85098

**Comment by vrld** [comment]
I've changed errhand to errorhandler as you suggested, but will try to reproduce the original error. Leaving this open for now.

**Comment by Positive07** [comment]
The new [`love.errorhandler`](https://love2d.org/wiki/love.errorhandler) returns a function which is then looped over every frame, hump doesn't respect this structure. It returns the value of `GS.errorhandler(...)` instead of `registry.errorhandler(...)` and that's why the loop fails the actual code is [here](https://github.com/vrld/hump/blob/master/gamestate.lua#L89L92):
```lua
registry[f] = love[f] or __NULL__
love[f] = function(...)
  registry[f](...)
  return GS[f](...)
end
```

For `errorhandler` at least, that should be:
```lua
registry[f] = love[f] or __NULL__
love[f] = function(...)
  GS[f](...)
  return registry[f](...)
end
```

**Comment by lemilonkh** [comment]
When can we expect this to be patched? I'll hotfix my version of hump for now I guess

**Comment by lemilonkh** [comment]
Sadly, @Positive07 's solution doesn't fix the crash for me...
I'm trying to use Love11's new audio effects or filters, but every time I set one on a Source the game crashes on me without an error message.
Any other workaround I could try?

Cheers,
Milan

**Comment by vrld** [comment]
Awesome! (For me anyways, not for you) Can you post a (preferably minimal) example code that reproduces this bug?

**Comment by vrld** [comment]
Since I can't reproduce the issue, but it is clearly related to love.errorhandler(), I just removed it from the list of callbacks to overwrite by default. Please reopen if this does not fix it.

**Comment by SystemLogoff** [comment]
Ah, this explains it. I noticed when you made a typo when switching gamestate, love would just close instead of showing the error. This only happened when 11 was released.

Using the version before this one:
```Gamestate.switch(not_a_real_table)```
will cause love to close without displaying an error on windows.

Anyway, thanks for patching!
